config/routes.rb
Rails.application.routes.draw do
  resources :qr_codes, only: [:new, :create, :show, :index]
  root to: 'qr_codes#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/qr_code_info.rb
# == Schema Information
#
# Table name: qr_code_infos
#
#  id                    :integer          not null, primary key
#  address               :string
#  city                  :string
#  first_name            :string
#  github_link           :string
#  info_type             :string
#  job_description       :string
#  job_place             :string
#  last_name             :string
#  personal_website_link :string
#  state                 :string
#  summary               :string
#  wifi_password         :string
#  wifi_ssid             :string
#  zip                   :string
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#
class QrCodeInfo < ApplicationRecord
  validates :info_type, presence: true
  validates :first_name, :last_name, :city, :address, :zip, :state, :job_place, :job_description, presence: true, if: :business_card?
  validates :wifi_ssid, :wifi_password, presence: true, if: :wifi?

  def business_card?
    info_type == 'Business Card'
  end

  def wifi?
    info_type == 'Wi-Fi'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/qr_codes_controller.rb
class QrCodesController < ApplicationController
  require 'rqrcode'
  require 'rqrcode_svg'

  def index
    @qr_codes = QrCodeInfo.all
  end
  
  def new
    @qr_code_info = QrCodeInfo.new
  end

  def show
    @qr_code_info = QrCodeInfo.find(params[:id])
    qr_data = {
      id: @qr_code_info.id,
      first_name: @qr_code_info.first_name,
      last_name: @qr_code_info.last_name,
      city: @qr_code_info.city,
      address: @qr_code_info.address,
      zip: @qr_code_info.zip,
      state: @qr_code_info.state,
      job_place: @qr_code_info.job_place,
      job_description: @qr_code_info.job_description,
      github_link: @qr_code_info.github_link,
      personal_website_link: @qr_code_info.personal_website_link
    }.to_json
    @qr_code = RQRCode::QRCode.new(qr_data)
    respond_to do |format|
      format.html
      format.svg {
        qr_code_svg = @qr_code.as_svg(offset: 0, color: '000', shape_rendering: 'crispEdges', module_size: 6)
        send_data qr_code_svg, type: 'image/svg+xml', disposition: 'inline'
      }
    end
  end
  
  
  
  def create
    @qr_code_info = QrCodeInfo.new(qr_code_info_params)
    if @qr_code_info.save
      redirect_to qr_code_path(@qr_code_info)
    else
      render :new
    end
  end
  
  

  private

  def generate_qr_code(qr_code_info)
    qr_data = {
      id: qr_code_info.id,
      first_name: qr_code_info.first_name,
      last_name: qr_code_info.last_name,
      city: qr_code_info.city,
      address: qr_code_info.address,
      zip: qr_code_info.zip,
      state: qr_code_info.state,
      job_place: qr_code_info.job_place,
      job_description: qr_code_info.job_description,
      github_link: qr_code_info.github_link,
      personal_website_link: qr_code_info.personal_website_link
    }.to_json

    RQRCode::QRCode.new(qr_data).as_svg(offset: 0, color: '000', shape_rendering: 'crispEdges', module_size: 6)
  end

  def qr_code_info_params
    params.require(:qr_code_info).permit(:first_name, :last_name, :city, :address, :zip, :state, :job_place, :job_description, :wifi_ssid, :wifi_password, :info_type, :github_link, :personal_website_link)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/qr_codes_helper.rb
module QrCodesHelper
  def generate_qr_code_svg(qr_code_info)
    require 'rqrcode'
    require 'rqrcode_svg'

    qr_data = qr_code_info.attributes.except("id", "created_at", "updated_at", "info_type").to_json
    qr_code = RQRCode::QRCode.new(qr_data)
    qr_code.as_svg(offset: 0, color: '000', shape_rendering: 'crispEdges', module_size: 6).to_s
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Base Rails</title>
    <%= csrf_meta_tags %>

    <!-- Expand the number of characters we can use in the document beyond basic ASCII 🎉 -->
    <meta charset="utf-8">

    <!-- Make it responsive to small screens -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>

  </head>

  <body>
  <nav>
  <ul>
    <li><%= link_to 'Create QR Code', new_qr_code_path %></li>
    <li><%= link_to 'All QR Codes', qr_codes_path %></li>
  </ul>
  </nav>

    <%= yield %>
  </body>
</html>

app/views/qr_codes/create.html.erb
<h1>QR Code Generated</h1>
<p>Find me in app/views/qr_codes/create.html.erb</p>

<%= link_to 'Go Back', new_qr_code_path, class: 'button' %>

app/views/qr_codes/index.html.erb
<h1>All QR Codes</h1>


<table>
  <thead>
    <tr>
      <th>Info Type</th>
      <th>Name</th>
      <th>City</th>
      <th>Address</th>
      <th>ZIP</th>
      <th>State</th>
      <th>Job Place</th>
      <th>Job Description</th>
      <th>Wi-Fi SSID</th>
      <th>Wi-Fi Password</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @qr_codes.each do |qr_code| %>
      <tr>
        <td><%= qr_code.info_type %></td>
        <td><%= qr_code.first_name %> <%= qr_code.last_name %></td>
        <td><%= qr_code.city %></td>
        <td><%= qr_code.address %></td>
        <td><%= qr_code.zip %></td>
        <td><%= qr_code.state %></td>
        <td><%= qr_code.job_place %></td>
        <td><%= qr_code.job_description %></td>
        <td><%= qr_code.wifi_ssid %></td>
        <td><%= qr_code.wifi_password %></td>
        <td><%= link_to 'Show', qr_code_path(qr_code) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/qr_codes/new.html.erb
<h1>Create QR Code</h1>

<%= form_with model: @qr_code_info, url: qr_codes_path, method: :post, local: true do |form| %>
  <%= form.label :info_type, "Information Type" %>
  <%= form.select :info_type, ['Business Card', 'Wi-Fi'], {}, onchange: "toggleFormFields(this.value);" %><br/><br/>

  <div id="business_card_fields">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %><br/>

    <%= form.label :last_name %>
    <%= form.text_field :last_name %><br/>

    <%= form.label :city %>
    <%= form.text_field :city %><br/>

    <%= form.label :address %>
    <%= form.text_field :address %><br/>

    <%= form.label :zip %>
    <%= form.text_field :zip %><br/>

    <%= form.label :state %>
    <%= form.text_field :state %><br/>

    <%= form.label :job_place %>
    <%= form.text_field :job_place %><br/>

    <%= form.label :job_description %>
    <%= form.text_field :job_description %><br/>

    <%= form.label :github_link, "GitHub" %>
    <%= form.url_field :github_link, placeholder: 'https://github.com/your_username' %><br/>

    <%= form.label :personal_website_link, "Personal Website" %>
    <%= form.url_field :personal_website_link, placeholder: 'https://yourpersonalwebsite.com' %><br/>
  </div>

  <div id="wifi_fields" style="display: none;">
    <%= form.label :wifi_ssid, "Wi-Fi SSID" %>
    <%= form.text_field :wifi_ssid %><br/>

    <%= form.label :wifi_password, "Wi-Fi Password" %>
    <%= form.text_field :wifi_password %><br/>
  </div>

  <%= form.submit 'Generate QR Code' %>
<% end %>

<script>
  function toggleFormFields(infoType) {
    if (infoType === 'Business Card') {
      document.getElementById('business_card_fields').style.display = 'block';
      document.getElementById('wifi_fields').style.display = 'none';
    } else if (infoType === 'Wi-Fi') {
      document.getElementById('business_card_fields').style.display = 'none';
      document.getElementById('wifi_fields').style.display = 'block';
    }
  }
</script>

app/views/qr_codes/show.html.erb
<h1>QR Code Information</h1>

<p>
  <strong>Name:</strong>
  <%= @qr_code_info.first_name %> <%= @qr_code_info.last_name %>
</p>

<p>
  <strong>City:</strong>
  <%= @qr_code_info.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @qr_code_info.address %>
</p>

<p>
  <strong>ZIP:</strong>
  <%= @qr_code_info.zip %>
</p>

<p>
  <strong>State:</strong>
  <%= @qr_code_info.state %>
</p>

<p>
  <strong>Job Place:</strong>
  <%= @qr_code_info.job_place %>
</p>

<p>
  <strong>Job Description:</strong>
  <%= @qr_code_info.job_description %>
</p>

<p>
  <strong>GitHub:</strong>
  <%= link_to @qr_code_info.github_link, @qr_code_info.github_link, target: '_blank' %>
</p>

<p>
  <strong>Personal Website:</strong>
  <%= link_to @qr_code_info.personal_website_link, @qr_code_info.personal_website_link, target: '_blank' %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @qr_code_info.summary %>
</p>

<p>
  <strong>QR Code:</strong>
  <%= raw @qr_code.as_svg %>
</p>